"$schema" = 'https://starship.rs/config-schema.json'

format = """$username$hostname$directory\
$battery$git_branch$git_status\
$c$rust$golang$nodejs\
$php$java$kotlin$haskell\
$python$docker_context$conda\
$time\n$character"""

palette = 'tokyonight_night'

[palettes.tokyonight_night]
color00 = '#13141C' # Background
color0  = '#1a1b26' # Background
color1  = '#414868' # Terminal Black
color2  = '#565f89' # Comments
color3  = '#9aa5ce' # Subtle FG / Text
color4  = '#a9b1d6' # Editor FG
color5  = '#c0caf5' # Terminal White / Variables
color6  = '#cfc9c2' # Semantic Parameters FG (subtle white/grey)
color7  = '#f7768e' # Terminal Red / Keywords
color8  = '#ff9e64' # Orange / Constants
color9  = '#e0af68' # Terminal Yellow / Parameters
color10 = '#9ece6a' # Green / Strings
color11 = '#73daca' # Terminal Green / Object Keys
color12 = '#7dcfff' # Terminal Cyan / Properties
color13 = '#2ac3de' # Teal / Lang Funcs
color14 = '#b4f9f8' # Bright Teal / Regex Literals
color15 = '#7aa2f7' # Terminal Blue / Func Names
color16 = '#bb9af7' # Terminal Magenta / Keywords
color17 = '#ffffff' # White

[os]
disabled = true
style = "fg:color17"

[os.symbols]
Amazon            = ""
Alpine            = ""
Android           = ""
Arch              = "󰣇"
Artix             = "󰣇"
CentOS            = ""
Debian            = "󰣚"
EndeavourOS       = ""
Fedora            = "󰣛"
Gentoo            = "󰣨"
Linux             = "󰌽"
Macos             = "󰀵"
Manjaro           = ""
Mint              = "󰣭"
NixOS             = ""
Pop               = ""
Raspbian          = "󰐿"
Redhat            = "󱄛"
RedHatEnterprise  = "󱄛"
SUSE              = ""
Ubuntu            = "󰕈"
Windows           = "󰍲"

[username]
show_always = true
style_user = "fg:color15"
style_root = "fg:color15"
format = "[╭─○ ](fg:color13)[󱙝](fg:color7)[ ](fg:color13)[$user]($style)"

[hostname]
style = "fg:color15"
trim_at = "-"
ssh_only = false
disabled = false
format = "[@](fg:color15)[$hostname]($style)"

[directory]
style = "fg:color16"
truncation_length = 0  # Set to 0 to show full path
truncate_to_repo = false  # Don't truncate to git repo root
disabled = false
format = "[ : ](fg:color13)[$path]($style)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:color8 bg:color0"
disabled = true
format = '[ : ](fg:color13)[$symbol $branch]($style)'

[git_status]
style = "fg:color13"
disabled = true
format = '[( : $all_status$ahead_behind)]($style)'

[nodejs]
symbol = " "
style = "fg:color12 bg:color0"
format = '[ : ](fg:color13)[$symbol($version)]($style)'

[c]
symbol = " "
style = "fg:color12 bg:color0"
format = '[ : ](fg:color13)[$symbol($version)]($style)'

[rust]
symbol = " "
style = "fg:color12 bg:color0"
format = '[ : ](fg:color13)[$symbol$version)]($style)'

[golang]
symbol = " "
style = "fg:color12 bg:color0"
format = '[ : ](fg:color13)[$symbol($version)]($style)'

[php]
symbol = " "
style = "fg:color12 bg:color0"
format = '[ : ](fg:color13)[$symbol($version)]($style)'

[java]
symbol = " "
style = "fg:color12 bg:color0"
format = '[ : ](fg:color13)[$symbol($version)]($style)'

[kotlin]
symbol = " "
style = "fg:color12 bg:color0"
format = '[ : ](fg:color13)[$symbol($version)]($style)'

[haskell]
symbol = " "
style = "fg:color12 bg:color0"
format = '[ : ](fg:color13)[$symbol($version)]($style)'

[python]
symbol = " "
style = "fg:color12 bg:color0"
format = '[ : ](fg:color13)[$symbol($version)]($style)'

[docker_context]
symbol = " "
style = "fg:color12 bg:color0"
format = '[ : ](fg:color13)[$symbol($context)]($style)'

[conda]
style = "fg:color12 bg:color0"
format = '[ : ](fg:color13)[$symbol($environment)]($style)'

[time]
disabled = false
time_format = "%H:%M"
style = "fg:color10"
format = '[ : ](fg:color13)[  $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[╰───────◇ ❯](fg:color13)"
error_symbol = "[╰───────◇ ✖](fg:color13)[](fg:color7)"
